#!/bin/bash
# Custom AppRun script for NipaPlay AppImage

HERE="$(dirname "$(readlink -f "${0}")")"
export LD_LIBRARY_PATH="${HERE}/lib:${HERE}/usr/lib:${LD_LIBRARY_PATH}"

# Set up data directory
export NIPAPLAY_DATA_DIR="${HERE}/data"

# The binary is in the root of the AppDir
exec "${HERE}/NipaPlay" "$@"
