#!/bin/bash
# Custom AppRun script for NipaPlay AppImage

SELF=$(readlink -f "$0")
HERE=${SELF%/*}
export PATH="${HERE}/usr/bin:${PATH}"
export LD_LIBRARY_PATH="${HERE}/usr/lib:${LD_LIBRARY_PATH}"

# Change to the binary directory
cd "${HERE}/usr/bin"

# Execute the binary (capital N, capital P)
exec ./NipaPlay "$@"
