name: 'Build Windows Package'
description: '构建 Windows 应用并生成 ZIP 和安装程序'
inputs:
  app-version:
    description: '应用版本号'
    required: true
outputs:
  zip-path:
    description: '生成的 ZIP 文件路径'
    value: ${{ steps.build.outputs.zip_path }}
  installer-path:
    description: '生成的安装程序路径'
    value: ${{ steps.installer.outputs.installer_path }}
runs:
  using: 'composite'
  steps:
    - name: Setup Chinese Font for Windows
      shell: pwsh
      run: |
        Write-Host "Setting up Chinese font for Windows build..."
        cd windows
        if (Test-Path "setup_font.bat") {
          Write-Host "Executing setup_font.bat..."
          cmd /c "setup_font.bat"
          if ($LASTEXITCODE -ne 0) {
            Write-Host "Warning: Font setup failed with exit code $LASTEXITCODE"
          } else {
            Write-Host "Font setup completed successfully"
          }
        } else {
          Write-Host "Warning: setup_font.bat not found, skipping font setup"
        }
        cd ..
    
    - name: Build Web and copy assets
      shell: bash
      run: |
        chmod +x build_and_copy_web.sh
        ./build_and_copy_web.sh

    - name: Download full libmpv package
      shell: pwsh
      run: |
        $customUrl = $env:LIBMPV_DOWNLOAD_URL
        $assetPattern = $env:LIBMPV_ASSET_PATTERN
        if ([string]::IsNullOrEmpty($assetPattern)) {
          $assetPattern = "mpv-dev-x86_64-v3.*\.7z"
        }
        choco install 7zip -y --no-progress
        $sevenZip = $null
        if ($env:ProgramFiles) {
          $candidate = Join-Path $env:ProgramFiles "7-Zip\7z.exe"
          if (Test-Path $candidate) {
            $sevenZip = $candidate
          }
        }
        if (-not $sevenZip -and ${env:ProgramFiles(x86)}) {
          $candidate = Join-Path ${env:ProgramFiles(x86)} "7-Zip\7z.exe"
          if (Test-Path $candidate) {
            $sevenZip = $candidate
          }
        }
        if (-not $sevenZip) {
          throw "未找到 7z.exe，请确保 7zip 安装成功"
        }
        $packagePath = "windows\libmpv-package.7z"
        $extractDir = "windows\libmpv-package"
        Remove-Item $packagePath -Force -ErrorAction SilentlyContinue
        Remove-Item $extractDir -Recurse -Force -ErrorAction SilentlyContinue
        New-Item -Path $extractDir -ItemType Directory -Force | Out-Null
        if ([string]::IsNullOrEmpty($customUrl)) {
          $releaseApi = "https://api.github.com/repos/shinchiro/mpv-winbuild-cmake/releases/latest"
          $headers = @{
            "User-Agent" = "NipaPlay-Build"
            "Accept"    = "application/vnd.github+json"
          }
          if ($env:GITHUB_TOKEN) {
            $headers["Authorization"] = "Bearer $($env:GITHUB_TOKEN)"
          }
          try {
            $release = Invoke-RestMethod -Uri $releaseApi -Headers $headers -UseBasicParsing
          } catch {
            throw "获取 mpv 最新版本信息失败：$($_.Exception.Message)"
          }
          $asset = $release.assets | Where-Object { $_.name -match $assetPattern } | Select-Object -First 1
          if (-not $asset) {
            $fallbackPattern = "mpv-dev-x86_64.*\.7z"
            $asset = $release.assets | Where-Object { $_.name -match $fallbackPattern } | Select-Object -First 1
          }
          if (-not $asset) {
            $fallbackPattern = "libmpv-shared-x86_64.*\.7z"
            $asset = $release.assets | Where-Object { $_.name -match $fallbackPattern } | Select-Object -First 1
          }
          if (-not $asset) {
            throw "未在 mpv 最新 release 中找到匹配的 libmpv 包"
          }
          $customUrl = $asset.browser_download_url
          Write-Host "选用 libmpv 资源：$($asset.name)"
        } else {
          Write-Host "使用自定义 libmpv 下载地址：$customUrl"
        }
        Write-Host "开始下载 libmpv 包：$customUrl"
        Invoke-WebRequest -Uri $customUrl -OutFile $packagePath -UseBasicParsing
        & $sevenZip x $packagePath "-o$extractDir" -y | Out-Null
        $dll = Get-ChildItem -Path $extractDir -Recurse -Filter "libmpv-2.dll" | Select-Object -First 1
        if (-not $dll) {
          throw "libmpv 包中未找到 libmpv-2.dll"
        }
        Copy-Item -Path $dll.FullName -Destination "windows\libmpv-2.dll" -Force
        Remove-Item $packagePath -Force -ErrorAction SilentlyContinue
        Write-Host "libmpv-2.dll 已下载并可用于后续打包"
    
    - name: Build Windows
      id: build
      shell: pwsh
      run: |
        flutter build windows --release
        $arch = "x64"
        $version = "${{ inputs.app-version }}"
        $DestDir = "build\windows\NipaPlay_${version}_Windows_x64"
        $SrcDir = "build\windows\x64\runner\Release"
        $CustomLib = "windows\libmpv-2.dll"
        if (!(Test-Path $SrcDir)) {
          throw "Windows 构建输出目录不存在：$SrcDir"
        }
        if (!(Test-Path $CustomLib)) {
          throw "未找到内置的完整版 libmpv：$CustomLib"
        }
        Copy-Item -Path $CustomLib -Destination "$SrcDir\libmpv-2.dll" -Force
        Write-Host "已将构建输出中的 libmpv-2.dll 替换为完整版"
        New-Item -Path $DestDir -ItemType Directory -Force
        Copy-Item -Path "$SrcDir\*" -Destination $DestDir -Recurse -Force
        Copy-Item -Path "windows\*.dll" -Destination $DestDir -Force
        $zipPath = "build\windows\NipaPlay_${version}_Windows_x64.zip"
        Compress-Archive -Path $DestDir -DestinationPath $zipPath -Force
        echo "zip_path=$zipPath" >> $env:GITHUB_OUTPUT

    - name: Install Inno Setup
      shell: pwsh
      run: |
        choco install innosetup --no-progress -y

    - name: Ensure Inno Setup Chinese language file
      shell: pwsh
      run: |
        $langFile = Join-Path "${env:ProgramFiles(x86)}" "Inno Setup 6\Languages\ChineseSimplified.isl"
        if (-not (Test-Path $langFile)) {
          Write-Host "ChineseSimplified.isl 缺失，尝试下载..."
          $langDir = Split-Path $langFile -Parent
          New-Item -ItemType Directory -Path $langDir -Force | Out-Null
          $urls = @(
            "https://raw.githubusercontent.com/jrsoftware/issrc/main/Files/Languages/ChineseSimplified.isl",
            "https://raw.githubusercontent.com/jrsoftware/issrc/main/Files/Languages/Unofficial/ChineseSimplified.isl",
            "https://raw.githubusercontent.com/jrsoftware/issrc/master/Files/Languages/ChineseSimplified.isl",
            "https://raw.githubusercontent.com/jrsoftware/issrc/master/Files/Languages/Unofficial/ChineseSimplified.isl"
          )
          foreach ($u in $urls) {
            try {
              Invoke-WebRequest -Uri $u -OutFile $langFile -UseBasicParsing -ErrorAction Stop
              Write-Host "下载成功：$u"
              break
            } catch {
              Write-Warning "下载失败：$u -- $($_.Exception.Message)"
            }
          }
          if (-not (Test-Path $langFile)) {
            $defaultLang = Join-Path (Split-Path $langDir -Parent) "Default.isl"
            if (-not (Test-Path $defaultLang)) {
              Write-Error "未找到 Default.isl，无法生成语言文件"
            }
            Copy-Item $defaultLang $langFile -Force
            Write-Warning "使用 Default.isl 作为占位，安装器语言将 fallback 为英文。"
          }
        } else {
          Write-Host "ChineseSimplified.isl 已存在：$langFile"
        }

    - name: Create Windows installer with Inno Setup
      id: installer
      shell: pwsh
      run: |
        $arch = "x64"
        $version = "${{ inputs.app-version }}"
        $buildDir = "build\windows\x64\runner\Release"
        if (-not (Test-Path $buildDir)) {
          throw "未找到 Windows 构建输出：$buildDir"
        }

        $artifactDir = "build\windows"
        New-Item -ItemType Directory -Path $artifactDir -Force | Out-Null

        $buildDir = (Resolve-Path $buildDir).Path
        $artifactDir = (Resolve-Path $artifactDir).Path

        $iconPath = "windows\runner\resources\app_icon.ico"
        if (-not (Test-Path $iconPath)) {
          throw "未找到安装器图标：$iconPath"
        }
        $iconPath = (Resolve-Path $iconPath).Path

        $licensePath = "LICENSE"
        if (-not (Test-Path $licensePath)) {
          throw "未找到 LICENSE 文件：$licensePath"
        }
        $licensePath = (Resolve-Path $licensePath).Path

        $installerScript = Join-Path $env:RUNNER_TEMP "NipaPlayInstaller.iss"
        $outputBaseName = "NipaPlay_${version}_Windows_${arch}_Setup"

        $assocId = "NipaPlay.VideoFile"
        $publisher = "MCDFSteve"

        @"
        #define MyAppName "NipaPlay"
        #define MyAppVersion "${version}"
        #define MyAppPublisher "${publisher}"
        #define MyAppExeName "NipaPlay.exe"
        #define MyAssocId "${assocId}"

        [Setup]
        AppId={{4A33C13F-61E9-4AB0-9F9F-4A2A6E9A6C55}}
        AppName={#MyAppName}
        AppVersion={#MyAppVersion}
        AppPublisher={#MyAppPublisher}
        DefaultDirName={code:GetAppDir}
        DefaultGroupName={#MyAppName}
        OutputDir="$artifactDir"
        OutputBaseFilename="$outputBaseName"
        SetupIconFile="$iconPath"
        UninstallDisplayIcon={app}\{#MyAppExeName}
        Compression=lzma
        SolidCompression=yes
        ArchitecturesAllowed=x64
        ArchitecturesInstallIn64BitMode=x64
        DisableWelcomePage=yes
        WizardStyle=modern
        PrivilegesRequired=lowest
        PrivilegesRequiredOverridesAllowed=dialog
        UsePreviousPrivileges=yes
        LicenseFile="$licensePath"

        [Languages]
        Name: "english"; MessagesFile: "compiler:Default.isl"
        Name: "chinesesimp"; MessagesFile: "compiler:Languages\ChineseSimplified.isl"

        [Tasks]
        Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked
        Name: "fileassoc"; Description: "将常见视频格式与 NipaPlay 关联"; Flags: unchecked

        [Files]
        Source: "$buildDir\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

        [Icons]
        Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
        Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

        [Registry]
        Root: HKCU; Subkey: "Software\Classes\.mp4"; ValueType: string; ValueName: ""; ValueData: "{#MyAssocId}"; Tasks: fileassoc; Flags: uninsdeletevalue
        Root: HKCU; Subkey: "Software\Classes\.mkv"; ValueType: string; ValueName: ""; ValueData: "{#MyAssocId}"; Tasks: fileassoc; Flags: uninsdeletevalue
        Root: HKCU; Subkey: "Software\Classes\.avi"; ValueType: string; ValueName: ""; ValueData: "{#MyAssocId}"; Tasks: fileassoc; Flags: uninsdeletevalue
        Root: HKCU; Subkey: "Software\Classes\.flv"; ValueType: string; ValueName: ""; ValueData: "{#MyAssocId}"; Tasks: fileassoc; Flags: uninsdeletevalue
        Root: HKCU; Subkey: "Software\Classes\.mov"; ValueType: string; ValueName: ""; ValueData: "{#MyAssocId}"; Tasks: fileassoc; Flags: uninsdeletevalue
        Root: HKCU; Subkey: "Software\Classes\.wmv"; ValueType: string; ValueName: ""; ValueData: "{#MyAssocId}"; Tasks: fileassoc; Flags: uninsdeletevalue
        Root: HKCU; Subkey: "Software\Classes\.m4v"; ValueType: string; ValueName: ""; ValueData: "{#MyAssocId}"; Tasks: fileassoc; Flags: uninsdeletevalue
        Root: HKCU; Subkey: "Software\Classes\.ts"; ValueType: string; ValueName: ""; ValueData: "{#MyAssocId}"; Tasks: fileassoc; Flags: uninsdeletevalue
        Root: HKCU; Subkey: "Software\Classes\.webm"; ValueType: string; ValueName: ""; ValueData: "{#MyAssocId}"; Tasks: fileassoc; Flags: uninsdeletevalue

        Root: HKCU; Subkey: "Software\Classes\{#MyAssocId}"; ValueType: string; ValueName: ""; ValueData: "NipaPlay 视频文件"; Tasks: fileassoc; Flags: uninsdeletekey
        Root: HKCU; Subkey: "Software\Classes\{#MyAssocId}\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\{#MyAppExeName},0"; Tasks: fileassoc
        Root: HKCU; Subkey: "Software\Classes\{#MyAssocId}\shell\open\command"; ValueType: string; ValueName: ""; ValueData: """{app}\{#MyAppExeName}"" ""%1"""; Tasks: fileassoc

        [Run]
        Filename: "{app}\{#MyAppExeName}"; Description: "启动 NipaPlay"; Flags: nowait postinstall skipifsilent

        [Code]
        function GetAppDir(Default: string): string;
        begin
          if IsAdminInstallMode then
            Result := ExpandConstant('{pf}\NipaPlay')
          else
            Result := ExpandConstant('{localappdata}\Programs\NipaPlay');
        end;
        "@ | Set-Content -Path $installerScript -Encoding utf8BOM

        $isccPath = Join-Path -Path "${env:ProgramFiles(x86)}" -ChildPath "Inno Setup 6\\ISCC.exe"
        if (-not (Test-Path $isccPath)) {
          throw "未找到 ISCC 可执行文件：$isccPath"
        }
        & $isccPath $installerScript

        $installerName = "${outputBaseName}.exe"
        $finalPath = "build\windows\$installerName"
        if (-not (Test-Path $finalPath)) {
          throw "Installer file was not created: $finalPath"
        }
        echo "installer_path=$finalPath" >> $env:GITHUB_OUTPUT

    - name: List Windows build artifacts
      shell: pwsh
      run: |
        Write-Host "=== Windows Build Artifacts ==="
        Get-ChildItem "build\windows\" -File | ForEach-Object {
          $sizeKB = [math]::Round($_.Length / 1KB, 2)
          Write-Host "$($_.Name) - ${sizeKB} KB"
        }
