name: 'Setup Flutter Environment'
description: '设置 Flutter 开发环境，包括 Java、FVM/Flutter 和获取版本信息'
inputs:
  java-version:
    description: 'Java 版本'
    required: false
    default: '21'
outputs:
  version:
    description: '从 pubspec.yaml 获取的应用版本'
    value: ${{ steps.get_version.outputs.version }}
runs:
  using: 'composite'
  steps:
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: ${{ inputs.java-version }}

    - name: Setup Dart (for FVM)
      uses: dart-lang/setup-dart@v1

    - name: Cache FVM & Pub cache (Linux/macOS)
      if: runner.os != 'Windows'
      uses: actions/cache@v4
      with:
        path: |
          ~/.fvm
          ~/.pub-cache
        key: ${{ runner.os }}-fvm-${{ hashFiles('.fvmrc') }}-${{ hashFiles('**/pubspec.lock') }}-${{ hashFiles('**/gradle-wrapper.properties') }}-v1
        restore-keys: |
          ${{ runner.os }}-fvm-

    - name: Cache FVM & Pub cache (Windows)
      if: runner.os == 'Windows'
      uses: actions/cache@v4
      with:
        path: |
          ${{ env.USERPROFILE }}\.fvm
          ${{ env.LOCALAPPDATA }}\Pub\Cache
        key: ${{ runner.os }}-fvm-${{ hashFiles('.fvmrc') }}-${{ hashFiles('**/pubspec.lock') }}-${{ hashFiles('**/gradle-wrapper.properties') }}-v1
        restore-keys: |
          ${{ runner.os }}-fvm-

    - name: Add Pub Cache bin to PATH (Linux/macOS)
      if: runner.os != 'Windows'
      shell: bash
      run: |
        echo "${PUB_CACHE:-$HOME/.pub-cache}/bin" >> "$GITHUB_PATH"

    - name: Add Pub Cache bin to PATH (Windows)
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        $pubCache = if ($env:PUB_CACHE) { $env:PUB_CACHE } else { "$env:LOCALAPPDATA\\Pub\\Cache" }
        Add-Content -Path $env:GITHUB_PATH -Value "$pubCache\\bin"
    
    - name: Install FVM
      shell: bash
      run: |
        dart pub global activate fvm

    - name: Install Flutter via FVM (Linux/macOS)
      if: runner.os != 'Windows'
      shell: bash
      run: |
        fvm install
        fvm use --force

    - name: Install Flutter via FVM (Windows)
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        fvm install
        fvm use --force

    - name: Add Flutter to PATH (Linux/macOS)
      if: runner.os != 'Windows'
      shell: bash
      run: |
        echo "$GITHUB_WORKSPACE/.fvm/flutter_sdk/bin" >> "$GITHUB_PATH"

    - name: Add Flutter to PATH (Windows)
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        Add-Content -Path $env:GITHUB_PATH -Value "$env:GITHUB_WORKSPACE\.fvm\flutter_sdk\bin"

    - name: Disable Flutter analytics
      shell: bash
      run: |
        flutter config --no-analytics
        flutter --version
    
    - name: Get app version
      id: get_version
      shell: bash
      run: |
        if [[ "$RUNNER_OS" == "Windows" ]]; then
          # Use PowerShell for Windows to extract version
          VERSION=$(pwsh -Command "(Get-Content pubspec.yaml | Select-String -Pattern '^version:' | ForEach-Object { \$_ -replace '^version: ', '' }).Trim()")
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
        else
          # Use grep/cut for Linux/macOS
          echo "version=$(grep '^version:' pubspec.yaml | cut -d ' ' -f 2)" >> $GITHUB_OUTPUT
        fi
    
    - name: Flutter Pub Get
      shell: bash
      run: |
        # Only set core.longpaths on Windows (not supported on macOS/Linux)
        if [[ "$RUNNER_OS" == "Windows" ]]; then
          git config --global core.longpaths true
        fi
        flutter pub get
